name: Count Files in Repository

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  
  workflow_dispatch:  # Позволяет запускать вручную из интерфейса GitHub

jobs:
  count-files:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Count files in repository
        id: count
        run: |
          file_count=$(find . -type f | wc -l)
          echo "Total files in repository: $file_count"
          echo "file_count=$file_count" >> $GITHUB_ENV

      - name: Display file count
        run: |
          echo "The repository contains ${{ env.file_count }} files."
