name: Count Files in Repository

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  
  workflow_dispatch:  # Позволяет запускать вручную из интерфейса GitHub 
  #на другой триггер другой job

jobs:
  count-files:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2 # actions - пространство имён, предопреленных гитхабом

      - name: Count files in repository
        # id: count # идентификатор шага, позволяет ссылаться на count на этот шаг из других шагов
        run: |
          file_count=$(find . -type f | wc -l)
          echo "Total files in repository: $file_count"
          echo "file_count=$file_count" >> $GITHUB_ENV

      - name: Display file count
        run: |
          echo "The repository contains ${{ env.file_count }} files."

  job-for-pull-request:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Pull Request-spec task
        run: | 
          echo "This job run only on pull request" 
