name: Count Files in Repository

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  count-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Count files in repository
        id: count
        run: |
          file_count=$(find . -type f | wc -l)
          echo "Total files in repository: $file_count"
          echo "file_count=$file_count" >> $GITHUB_ENV

      - name: Display file count
        run: |
          echo "The repository contains ${{ env.file_count }} files."

  job-for-pull-request:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        event: [pull_request]
    if: contains(strategy.matrix.event, github.event_name)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Pull Request-specific task
        run: |
          echo "This job runs only on pull request"
